In [3]:
import pandas as pd
df = pd.read_csv("maint.csv")
df.head()

              datetime  machineID   comp
0  2014-06-01 06:00:00          1  comp2
1  2014-07-16 06:00:00          1  comp4
2  2014-07-31 06:00:00          1  comp3
3  2014-12-13 06:00:00          1  comp1
4  2015-01-05 06:00:00          1  comp4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   3286 non-null   object
 1   machineID  3286 non-null   int64
 2   comp       3286 non-null   object
dtypes: int64(1), object(2)
memory usage: 77.1+ KB

In [6]:
df.isnull().sum()

datetime     0
machineID    0
comp         0
year         0
month        0
day          0
hour         0
dtype: int64

In [5]:
df['datetime'] = pd.to_datetime(df['datetime'])

df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour

In [8]:
df = pd.get_dummies(df,drop_first=True,dtype=int)
df.head()

,datetime,machineID,year,month,day,hour,comp_comp2,comp_comp3,comp_comp4
0,2014-06-01 06:00:00,1,2014,6,1,6,1,0,0
1,2014-07-16 06:00:00,1,2014,7,16,6,0,0,1
2,2014-07-31 06:00:00,1,2014,7,31,6,0,1,0
3,2014-12-13 06:00:00,1,2014,12,13,6,0,0,0
4,2015-01-05 06:00:00,1,2015,1,5,6,0,0,1

In [9]:
df = df.drop('datetime', axis=1)
df.head()

   machineID  year  month  day  hour  comp_comp2  comp_comp3  comp_comp4
0          1  2014      6    1     6           1           0           0
1          1  2014      7   16     6           0           0           1
2          1  2014      7   31     6           0           1           0
3          1  2014     12   13     6           0           0           0
4          1  2015      1    5     6           0           0           1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   machineID   3286 non-null   int64
 1   year        3286 non-null   int32
 2   month       3286 non-null   int32
 3   day         3286 non-null   int32
 4   hour        3286 non-null   int32
 5   comp_comp2  3286 non-null   int64
 6   comp_comp3  3286 non-null   int64
 7   comp_comp4  3286 non-null   int64
dtypes: int32(4), int64(4)
memory usage: 154.2 KB