In [1]:
import pandas as pd
import numpy as np

In [3]:
failures = pd.read_csv("../Data/failures.csv")

In [4]:
failures["datetime"] = pd.to_datetime(failures["datetime"])

In [5]:
failures.head()

             datetime  machineID failure
0 2015-01-05 06:00:00          1   comp4
1 2015-03-06 06:00:00          1   comp1
2 2015-04-20 06:00:00          1   comp2
3 2015-06-19 06:00:00          1   comp4
4 2015-09-02 06:00:00          1   comp4

In [6]:
failures = failures.sort_values(["machineID", "datetime"]).reset_index(drop=True)

In [7]:
failure_dummies = pd.get_dummies(failures["failure"], prefix="failure")
failures = pd.concat([failures, failure_dummies], axis=1)

In [8]:
failures.head()

,datetime,machineID,failure,failure_comp1,failure_comp2,failure_comp3,failure_comp4
0,2015-01-05 06:00:00,1,comp4,False,False,False,True
1,2015-03-06 06:00:00,1,comp1,True,False,False,False
2,2015-04-20 06:00:00,1,comp2,False,True,False,False
3,2015-06-19 06:00:00,1,comp4,False,False,False,True
4,2015-09-02 06:00:00,1,comp4,False,False,False,True

In [9]:
failures["days_since_last_failure"] = (
    failures.groupby("machineID")["datetime"]
    .transform(lambda x: x.diff().dt.total_seconds() / (3600 * 24))
)
#The machine that failed recently is not

In [ ]:
failures["cumulative_failures"] = failures.groupby("machineID").cumcount() + 1

_IncompleteInputError: incomplete input (3234286417.py, line 2)