In [15]:
import pandas as pd
import datetime as dt

In [16]:
df= pd.read_csv('Data/telemetry.csv')
df.head()

,datetime,machineID,volt,rotate,pressure,vibration
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847
3,2015-01-01 09:00:00,1,162.462833,346.149335,109.248561,41.122144
4,2015-01-01 10:00:00,1,157.610021,435.376873,111.886648,25.990511

In [17]:
df.shape

(876100, 6)

In [18]:
df.nunique()

datetime       8761
machineID       100
volt         876100
rotate       876100
pressure     876100
vibration    876100
dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876100 entries, 0 to 876099
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   datetime   876100 non-null  object
 1   machineID  876100 non-null  int64
 2   volt       876100 non-null  float64
 3   rotate     876100 non-null  float64
 4   pressure   876100 non-null  float64
 5   vibration  876100 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 40.1+ MB

In [21]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [24]:
df['Year'] = df['datetime'].dt.year
df['Month'] = df['datetime'].dt.month
df['Day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['day_of_week'] = df['datetime'].dt.dayofweek
df.drop('datetime', axis=1, inplace=True)

In [25]:
df.head()

,machineID,volt,rotate,pressure,vibration,Year,Month,Day,hour,day_of_week
0,1,176.217853,418.504078,113.077935,45.087686,2015,1,1,6,3
1,1,162.879223,402.747490,95.460525,43.413973,2015,1,1,7,3
2,1,170.989902,527.349825,75.237905,34.178847,2015,1,1,8,3
3,1,162.462833,346.149335,109.248561,41.122144,2015,1,1,9,3
4,1,157.610021,435.376873,111.886648,25.990511,2015,1,1,10,3

In [26]:
outlier_columns = ['volt', 'rotate', 'pressure', 'vibration']
for i in outlier_columns:
  q1 = df[i].quantile(0.25)
  q3 = df[i].quantile(0.75)
  iqr = q3 - q1
  upper_limit = q3 + 1.5 * iqr
  lower_limit = q1 - 1.5 * iqr
  df[i] = df[i].clip(lower = lower_limit, upper = upper_limit)

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
machineID,876100.0,50.500000,28.866087,1.000000,25.750000,50.500000,75.250000,100.000000
volt,876100.0,170.759145,15.364967,129.255578,160.304927,170.607338,181.004493,212.053843
rotate,876100.0,446.714898,52.068046,307.499385,412.305714,447.558150,482.176600,586.982929
pressure,876100.0,100.766627,10.710065,72.412605,93.498181,100.425559,107.555231,128.640807
vibration,876100.0,40.361722,5.271617,26.265839,36.777299,40.237247,43.784938,54.296398
Year,876100.0,2015.000799,0.028255,2015.000000,2015.000000,2015.000000,2015.000000,2016.000000
Month,876100.0,6.525397,3.448162,1.000000,4.000000,7.000000,10.000000,12.000000
Day,876100.0,15.718868,8.797156,1.000000,8.000000,16.000000,23.000000,31.000000
hour,876100.0,11.499372,6.922045,0.000000,6.000000,11.000000,17.000000,23.000000
day_of_week,876100.0,3.000799,1.997345,0.000000,1.000000,3.000000,5.000000,6.000000